export const GLOBAL_MAP_INSTANS = "GLOBAL_MAP_INSTANS";
export const POPUP_INSTANS = "POPUP_INSTANS";
export const POPUP_HOVER_INSTANS = "POPUP_HOVER_INSTANS";
export const ONLOUDED_MAP = "ONLOUDED_MAP";




